[toolchain]
anchor_version = "0.30.1-afcbaedac69d23544cad177acfbe10b325cf0a06" 
solana_version = "2.1.4"

[features]
seeds = false
skip-lint = false

[programs.localnet]
clubhouse = "C1ubv5AC5w7Eh3iHpEt2BXZ1g3eARQtMRgmE2AXfznSg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/keys/club_dep.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
